- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: "dedicated"
      operator: "Equal"
      value: "mainnet"
      effect: "PreferNoSchedule"

- op: add
  path: /spec/template/spec/affinity
  value:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: cardano_node_type
            operator: In
            values:
            - haskell
        topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - mainnet
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: dedicated
              operator: In
              values:
              - mainnet
