---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gc-totem-ms
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gc-totem-ms
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","secrets"]
  verbs: ["delete", "get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gc-totem-ms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gc-totem-ms
subjects:
- kind: ServiceAccount
  name: gc-totem-ms
