namespace: cardano-iohk-tn
#namePrefix: ptn0-
commonLabels:
  environment: development
  cardano_network: testnet
  cardano_node_type: haskell
  project_name: iohk-tn
commonAnnotations:
  note: this is your local k8s cluster!
bases:
- ../../base/common
- ../../base/passive-node
- ../../base/leader-node
- resources/gc-totem-ms
resources:
- resources/daemonset-topologyUpdater.yaml
patches:
# common
- path: patches/deployment-container-resources.yaml
  target:
    kind: StatefulSet
- path: patches/deployment-container-port.yaml
  target:
    kind: StatefulSet
- path: patches/deployment-container-env.yaml
  target:
    kind: StatefulSet
# passive-node
- path: patches/configmap-configuration.yaml
  target:
    kind: ConfigMap
    name: passive-node
- path: patches/configmap-genesis.yaml
  target:
    kind: ConfigMap
    name: passive-node
- path: patches/configmap-passive-node-topology.yaml
  target:
    kind: ConfigMap
    name: passive-node
- path: patches/service-passive-node-nodeport.yaml
  target:
    kind: Service
    name: passive-node
- path: patches/service-passive-node-headless.yaml
  target:
    kind: Service
    name: passive-node-headless
- path: patches/deployment-image-passive-node.yaml
  target:
    kind: StatefulSet
    name: passive-node
- path: patches/deployment-passive-node-replicas.yaml
  target:
    kind: StatefulSet
    name: passive-node
- path: patches/deployment-passive-pvc-templates.yaml
  target:
    kind: StatefulSet
    name: passive-node
# leader-node
- path: patches/configmap-configuration.yaml
  target:
    kind: ConfigMap
    name: leader-node
- path: patches/configmap-genesis.yaml
  target:
    kind: ConfigMap
    name: leader-node
- path: patches/deployment-image-leader-node.yaml
  target:
    kind: StatefulSet
    name: leader-node
- path: patches/deployment-leader-node-replicas.yaml
  target:
    kind: StatefulSet
    name: leader-node
- path: patches/service-leader-node.yaml
  target:
    kind: Service
    name: leader-node
- path: patches/deployment-leader-pvc-templates.yaml
  target:
    kind: StatefulSet
    name: leader-node
