- op: replace
  path: /spec/template/spec/containers/0/image
  value:
    repsistance/cardano-node:iohk-fftn-passive-202006120043-02f358d-c17483d

- op: replace
  path: /spec/template/spec/initContainers/0/image
  value:
    repsistance/cardano-node:iohk-fftn-passive-202006120043-02f358d-c17483d
