apiVersion: batch/v1
kind: CronJob
metadata:
  name: gc-totem-ms-secret-mgmt
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 540
      template:
        spec:
          serviceAccountName: gc-totem-ms
          containers:
          - name: gc-totem-ms-secret-mgmt
            command: ["bash", "-x", "/configmap/update-pool-keys"]
            image: gimbalabs/cardano-db-sync-init-container:1.35.3-0
            volumeMounts:
            - name: gc-totem-ms-configmap
              mountPath: /configmap
            - name: gc-totem-ms-priv
              mountPath: /priv
            env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          restartPolicy: Never
          volumes:
          - name: gc-totem-ms-configmap
            configMap:
              name: gc-totem-ms-configmap
          - name: gc-totem-ms-priv
            persistentVolumeClaim:
              claimName: gc-totem-ms-priv
