---
apiVersion: v1
kind: Service
metadata:
  name: leader-node-metrics
  labels:
    app.kubernetes.io/name: leader-node-metrics
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: metrics
    port: 13788
    targetPort: 13788
    protocol: TCP
  selector:
    io.kompose.service: leader-node
