---
apiVersion: v1
kind: Service
metadata:
  name: leader-node
  labels:
    io.kompose.service: leader-node
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
  - name: p2p
    port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    io.kompose.service: leader-node

---
apiVersion: v1
kind: Service
metadata:
  name: leader-node-metrics
  labels:
    app.kubernetes.io/name: leader-node-metrics
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: metrics
    port: 12798
    targetPort: 12798
    protocol: TCP
  selector:
    io.kompose.service: leader-node
