apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: leader-node
  name: leader-node
spec:
  serviceName: leader-node
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leader-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: leader-node
    spec:
      initContainers:
      - name: configure
        command: ["bash", "/configmap/initContainer-entrypoint"]
        image: rcmorano/cardano-node:guild-ops-ptn0-leader
        imagePullPolicy: "Always"
        env:
        - name: CNODE_PORT
          value: "6000"
        - name: CNODE_HOST_ADDR
          value: "0.0.0.0"
        - name: CNODE_USE_CONFIGMAP
          value: "true"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /opt/cardano/cnode/files.pvc
          name: leader-node-files
        - mountPath: /opt/cardano/cnode/db
          name: leader-node-db
        - mountPath: /configmap
          name: leader-node-configmap
      containers:
      - command: ["bash", "-c", "sudo -EHu nobody bash -c 'source ~/.baids/baids && ${NETWORK}-cnode-run-as-${CNODE_ROLE}'"]
        env:
        - name: CNODE_PORT
          value: "6000"
        image: rcmorano/cardano-node:guild-ops-ptn0-leader
        imagePullPolicy: "Always"
        name: leader-node
        ports:
        - containerPort: 6000
        - containerPort: 13788
        resources:
          #limits:
          #  memory: 700Mi
          requests:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - mountPath: /opt/cardano/cnode/files
          name: leader-node-files
        - mountPath: /opt/cardano/cnode/db
          name: leader-node-db
        - mountPath: /configmap
          name: leader-node-configmap
        - mountPath: /opt/cardano/cnode/priv/pool/default
          name: pool-keys
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: leader-node-configmap
        configMap:
          name: leader-node
      - name: pool-keys
        secret:
          secretName: pool-keys
          items:
          - key: hot.skey
            path: hot.skey
          - key: vrf.skey
            path: vrf.skey
          - key: op.cert
            path: op.cert
  volumeClaimTemplates:
  - metadata:
      name: leader-node-files
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-s3
      resources:
        requests:
          storage: 100Mi
#  - metadata:
#      name: leader-node-priv
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: csi-s3
#      resources:
#        requests:
#          storage: 100Mi
  - metadata:
      name: leader-node-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

