- op: replace
  path: /spec/template/spec/containers/0/env
  value:
    - name: CNODE_PORT
      value: "30201"
    - name: CNODE_HOST_ADDR
      value: "0.0.0.0"
- op: replace
  path: /spec/template/spec/initContainers/0/env
  value:
    - name: CNODE_PORT
      value: "30201"
