apiVersion: v1
kind: ConfigMap
metadata:
  name: clio1-topology-updater
  namespace: cardano
  labels:
    app: clio1-topology-updater
data:
  topology-updater: |
    set -x

    source /etc/profile.d/docker-environment.sh

    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    
    blockNo=$(curl -s passive-node-metrics.${NAMESPACE}.svc.cluster.local:13788/metrics | grep cardano_node_ChainDB_metrics_blockNum_int | awk '{print $NF}')
    
    curl -s "${BASE_URL}/?port=${CNODE_PORT}&blockNo=${blockNo}&hostname=${CNODE_HOSTNAME}&valency=${CNODE_VALENCY}&magic=${TESTNET_MAGIC}"
