namespace: cardano-ptn0
#namePrefix: ptn0-
commonLabels:
  environment: production
  cardano_network: ptn0
  cardano_node_type: haskell
  project_name: guild-ops
commonAnnotations:
  note: this is your local k8s cluster!
bases:
- ../../base/common
- ../../base/passive-node
- ../../base/leader-node
patches:
# common
- path: patches/configmap-genesis.yaml
  target:
    kind: ConfigMap
- path: patches/deployment-container-port.yaml
  target:
    kind: StatefulSet
- path: patches/deployment-container-env.yaml
  target:
    kind: StatefulSet
- path: patches/servicemonitor-ns-selector.yaml
  target:
    kind: ServiceMonitor
# passive-node
- path: patches/configmap-passive-node-topology.yaml
  target:
    kind: ConfigMap
    name: passive-node
- path: patches/service-passive-node-nodeport.yaml
  target:
    kind: Service
    name: passive-node
- path: patches/service-passive-node-headless.yaml
  target:
    kind: Service
    name: passive-node-headless
- path: patches/deployment-image-passive-node.yaml
  target:
    kind: StatefulSet
    name: passive-node
# leader-node
- path: patches/deployment-image-leader-node.yaml
  target:
    kind: StatefulSet
    name: leader-node
- path: patches/service-leader-node.yaml
  target:
    kind: Service
    name: leader-node
